/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    courses: Course;
    'course-sections': CourseSection;
    activities: Activity;
    enrollments: Enrollment;
    community: Community;
    tenants: Tenant;
    'brand-settings': BrandSetting;
    'puck-templates': PuckTemplate;
    'puck-ai-prompts': PuckAiPrompt;
    'puck-ai-context': PuckAiContext;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'pages';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-sections': CourseSectionsSelect<false> | CourseSectionsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    community: CommunitySelect<false> | CommunitySelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'brand-settings': BrandSettingsSelect<false> | BrandSettingsSelect<true>;
    'puck-templates': PuckTemplatesSelect<false> | PuckTemplatesSelect<true>;
    'puck-ai-prompts': PuckAiPromptsSelect<false> | PuckAiPromptsSelect<true>;
    'puck-ai-context': PuckAiContextSelect<false> | PuckAiContextSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Vendure Customer id this account is derived from
   */
  vendureCustomerId?: string | null;
  /**
   * Display name, mirrored from the Vendure customer
   */
  name?: string | null;
  /**
   * Admin and Editor grant Admin Panel access. Customer does not.
   */
  roles: ('admin' | 'editor' | 'customer')[];
  accountType?: ('b2c' | 'b2b') | null;
  /**
   * Community invite issued to this customer
   */
  sharkeyInviteCode?: string | null;
  /**
   * When the community invite was issued
   */
  sharkeyInviteIssuedAt?: string | null;
  /**
   * Grants access to private docs/Starlight library
   */
  hasLibraryAccess?: boolean | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The three brands. Adding one here does not route it — see src/lib/tenants.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Display name, e.g. "Orbit Labs".
   */
  name: string;
  /**
   * Short key: tlr, tgp or snm. Must match the code in src/lib/tenants.ts and the page-tree folder name.
   */
  code: string;
  /**
   * Primary public hostname, e.g. orbitlabs.example.
   */
  domain?: string | null;
  /**
   * Every hostname this brand answers on, including parked and vanity domains. Informational — routing uses the static map.
   */
  hostnames?:
    | {
        hostname: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Synced from Vendure. READ-ONLY.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  vendureId: string;
  name: string;
  slug: string;
  description?: string | null;
  price?: number | null;
  sku?: string | null;
  syncStatus?: ('synced' | 'syncing' | 'error') | null;
  lastSyncedAt?: string | null;
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Learning courses with sections and activities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g. "intro-to-orbitlabs")
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  sections?: (number | CourseSection)[] | null;
  accessLevel?: ('free' | 'subscriber' | 'premium') | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hierarchical grouping of activities within courses
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-sections".
 */
export interface CourseSection {
  id: number;
  title: string;
  /**
   * Brief summary shown in course outlines
   */
  description?: string | null;
  /**
   * Display order within the course
   */
  order?: number | null;
  activities?: (number | Activity)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Interactive learning activities with 3D or video content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mediaType: 'gltf' | 'remotion' | 'none';
  /**
   * URL to GLTF/GLB file (from Media upload)
   */
  gltfUrl?: string | null;
  /**
   * Remotion composition name
   */
  remotionComposition?: string | null;
  order?: number | null;
  /**
   * Estimated duration in minutes
   */
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User enrollments in courses with role-based access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  user: number | User;
  course: number | Course;
  role: 'student' | 'teacher' | 'ta' | 'manager';
  enrolledAt?: string | null;
  /**
   * Completion percentage (0-100) — recomputed from completedActivities by the completion route
   */
  progress?: number | null;
  /**
   * Activities the learner has marked complete (drives progress)
   */
  completedActivities?: (number | Activity)[] | null;
  status?: ('active' | 'completed' | 'dropped') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community".
 */
export interface Community {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Header, footer and identity for the selected brand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings".
 */
export interface BrandSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Shown in the header and the browser tab for this brand.
   */
  siteName: string;
  /**
   * Optional short line under the wordmark, e.g. "RESEARCH".
   */
  tagline?: string | null;
  enable_auth?: boolean | null;
  /**
   * Header logo for this brand. Recommended: SVG or transparent PNG.
   */
  logo?: (number | null) | Media;
  /**
   * Links displayed in this brand’s header navigation.
   */
  navLinks?:
    | {
        label: string;
        /**
         * Relative path (e.g. /about) or full URL (e.g. https://example.com)
         */
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer text for this brand (e.g. copyright notice).
   */
  footerText?: string | null;
  /**
   * Social media links displayed in this brand’s footer.
   */
  socialLinks?:
    | {
        platform: 'twitter' | 'github' | 'discord' | 'youtube' | 'linkedin' | 'instagram' | 'mastodon' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable component templates for the visual editor
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-templates".
 */
export interface PuckTemplate {
  id: number;
  /**
   * A descriptive name for this template
   */
  name: string;
  /**
   * Optional description of what this template contains
   */
  description?: string | null;
  /**
   * Category for organizing templates (e.g., "Hero", "Footer", "CTA")
   */
  category?: string | null;
  /**
   * Serialized Puck component data
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional thumbnail URL for template preview
   */
  thumbnail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-ai-prompts".
 */
export interface PuckAiPrompt {
  id: number;
  /**
   * Display label for the prompt (e.g., "Landing page")
   */
  label: string;
  /**
   * The actual prompt text sent to the AI
   */
  prompt: string;
  /**
   * Optional category for grouping prompts (e.g., "Marketing", "Product")
   */
  category?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Business context for AI page generation. Add entries for brand guidelines, tone of voice, product info, etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-ai-context".
 */
export interface PuckAiContext {
  id: number;
  /**
   * Name for this context block (e.g., "Brand Guidelines", "Tone of Voice")
   */
  name: string;
  /**
   * The context content in markdown format. Use headers (##) to organize, lists for guidelines, etc.
   */
  content: string;
  /**
   * Category for organizing context blocks
   */
  category?: ('brand' | 'tone' | 'product' | 'industry' | 'technical' | 'patterns' | 'other') | null;
  /**
   * Include this context in AI prompts. Uncheck to temporarily disable.
   */
  enabled?: boolean | null;
  /**
   * Order in the context (lower numbers appear earlier in the prompt)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Auto-generated from folder path + page segment
   */
  slug: string;
  /**
   * Overall page structure and layout style
   */
  pageLayout: 'default' | 'landing' | 'full-width';
  /**
   * Which editor was used to create this page
   */
  editorVersion?: ('legacy' | 'puck') | null;
  /**
   * Mark this page as the homepage
   */
  isHomepage?: boolean | null;
  /**
   * Puck editor data - managed via visual editor
   */
  puckData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?: {
    /**
     * Override the page title for search engines
     */
    title?: string | null;
    /**
     * Description shown in search engine results
     */
    description?: string | null;
    /**
     * Image shown when sharing on social media
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page
     */
    noindex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    nofollow?: boolean | null;
    /**
     * Exclude this page from the XML sitemap
     */
    excludeFromSitemap?: boolean | null;
  };
  /**
   * Configure conversion tracking for analytics
   */
  conversionTracking?: {
    /**
     * Check this if this page represents a completed conversion (e.g., thank you page)
     */
    isConversionPage?: boolean | null;
    /**
     * Type of conversion this page represents
     */
    conversionType?: ('lead' | 'registration' | 'purchase' | 'donation' | 'newsletter' | 'contact' | 'custom') | null;
    /**
     * Monetary value of this conversion (0 for non-monetary conversions)
     */
    conversionValue?: number | null;
  };
  /**
   * URL segment for this page (auto-generated from title if empty)
   */
  pageSegment?: string | null;
  sortOrder?: number | null;
  /**
   * Previous URLs for this page (auto-tracked)
   */
  slugHistory?:
    | {
        slug: string;
        changedAt: string;
        reason?: ('move' | 'rename' | 'regenerate' | 'restore' | 'manual' | 'edit-url') | null;
        id?: string | null;
      }[]
    | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'pages';
          value: number | Page;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'pages'[] | null;
  /**
   * URL path segment (e.g., "appeals" for /appeals/...)
   */
  pathSegment?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-sections';
        value: number | CourseSection;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'community';
        value: number | Community;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'brand-settings';
        value: number | BrandSetting;
      } | null)
    | ({
        relationTo: 'puck-templates';
        value: number | PuckTemplate;
      } | null)
    | ({
        relationTo: 'puck-ai-prompts';
        value: number | PuckAiPrompt;
      } | null)
    | ({
        relationTo: 'puck-ai-context';
        value: number | PuckAiContext;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  vendureCustomerId?: T;
  name?: T;
  roles?: T;
  accountType?: T;
  sharkeyInviteCode?: T;
  sharkeyInviteIssuedAt?: T;
  hasLibraryAccess?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  vendureId?: T;
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  sku?: T;
  syncStatus?: T;
  lastSyncedAt?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  sections?: T;
  accessLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-sections_select".
 */
export interface CourseSectionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  activities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  mediaType?: T;
  gltfUrl?: T;
  remotionComposition?: T;
  order?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  role?: T;
  enrolledAt?: T;
  progress?: T;
  completedActivities?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community_select".
 */
export interface CommunitySelect<T extends boolean = true> {
  title?: T;
  content?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  domain?: T;
  hostnames?:
    | T
    | {
        hostname?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings_select".
 */
export interface BrandSettingsSelect<T extends boolean = true> {
  tenant?: T;
  siteName?: T;
  tagline?: T;
  enable_auth?: T;
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-templates_select".
 */
export interface PuckTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  category?: T;
  content?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-ai-prompts_select".
 */
export interface PuckAiPromptsSelect<T extends boolean = true> {
  label?: T;
  prompt?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-ai-context_select".
 */
export interface PuckAiContextSelect<T extends boolean = true> {
  name?: T;
  content?: T;
  category?: T;
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  pageLayout?: T;
  editorVersion?: T;
  isHomepage?: T;
  puckData?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        nofollow?: T;
        excludeFromSitemap?: T;
      };
  conversionTracking?:
    | T
    | {
        isConversionPage?: T;
        conversionType?: T;
        conversionValue?: T;
      };
  pageSegment?: T;
  sortOrder?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        changedAt?: T;
        reason?: T;
        id?: T;
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  pathSegment?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}